[package]
name = "bigbrother"
version = "0.1.0"
edition = "2024"

[dependencies]
migration = { path = "../migration" }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
trace_id = { workspace = true }
backtrace = { workspace = true }
clap = { workspace = true }
time = { workspace = true }
reqwest = { workspace = true }
reqwest-middleware = { workspace = true }
reqwest-retry = { workspace = true }
thiserror = { workspace = true }
regex = { workspace = true }
lingua = { workspace = true }
teloxide = { workspace = true }
futures = { workspace = true }
sea-orm = { workspace = true }
chrono = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
rsa = { workspace = true }

[dev-dependencies]
wiremock = { workspace = true }
