curl 'https://127.0.0.1:8096/emby/Shows/16182/Episodes?IsVirtualUnaired=false&IsMissing=false&UserId=b4be2e3b7e1b460da351257f18240d41&Fields=ProductionYear%2CPremiereDate%2CContainer%2CPresentationUniqueKey&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Google+Chrome+Windows&X-Emby-Device-Id=cbe83d8b-9ec9-487f-a0b4-6bf5305035f8&X-Emby-Client-Version=4.9.3.0&X-Emby-Token=token&X-Emby-Language=zh-cn' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'priority: u=1, i' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' ;
curl 'https://127.0.0.1:8096/emby/Items/16184/PlaybackInfo?UserId=b4be2e3b7e1b460da351257f18240d41&StartTimeTicks=18887893570&IsPlayback=true&AutoOpenLiveStream=true&AudioStreamIndex=1&MediaSourceId=mediasource_16184&MaxStreamingBitrate=200000000&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Google+Chrome+Windows&X-Emby-Device-Id=cbe83d8b-9ec9-487f-a0b4-6bf5305035f8&X-Emby-Client-Version=4.9.3.0&X-Emby-Token=token&X-Emby-Language=zh-cn&reqformat=json' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: text/plain' \
  -H 'origin: https://127.0.0.1:8096' \
  -H 'priority: u=1, i' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' \
  --data-raw '{"DeviceProfile":{"MaxStaticBitrate":200000000,"MaxStreamingBitrate":200000000,"MusicStreamingTranscodingBitrate":192000,"DirectPlayProfiles":[{"Container":"mp4,m4v","Type":"Video","VideoCodec":"h264,hevc,av1,vp8,vp9","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"mkv","Type":"Video","VideoCodec":"h264,hevc,av1,vp8,vp9","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"flv","Type":"Video","VideoCodec":"h264","AudioCodec":"aac,mp3"},{"Container":"3gp","Type":"Video","VideoCodec":"","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"mov","Type":"Video","VideoCodec":"h264","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"opus","Type":"Audio"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3"},{"Container":"mp2,mp3","Type":"Audio","AudioCodec":"mp2"},{"Container":"aac","Type":"Audio","AudioCodec":"aac"},{"Container":"m4a","AudioCodec":"aac","Type":"Audio"},{"Container":"mp4","AudioCodec":"aac","Type":"Audio"},{"Container":"flac","Type":"Audio"},{"Container":"webma,webm","Type":"Audio"},{"Container":"wav","Type":"Audio","AudioCodec":"PCM_S16LE,PCM_S24LE"},{"Container":"ogg","Type":"Audio"},{"Container":"webm","Type":"Video","AudioCodec":"vorbis,opus","VideoCodec":"av1,VP8,VP9"}],"TranscodingProfiles":[{"Container":"aac","Type":"Audio","AudioCodec":"aac","Context":"Streaming","Protocol":"hls","MaxAudioChannels":"2","MinSegments":"1","BreakOnNonKeyFrames":false},{"Container":"aac","Type":"Audio","AudioCodec":"aac","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"opus","Type":"Audio","AudioCodec":"opus","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"wav","Type":"Audio","AudioCodec":"wav","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"opus","Type":"Audio","AudioCodec":"opus","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"aac","Type":"Audio","AudioCodec":"aac","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"wav","Type":"Audio","AudioCodec":"wav","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mkv","Type":"Video","AudioCodec":"mp3,aac,opus,flac,vorbis","VideoCodec":"h264,hevc,av1,vp8,vp9","Context":"Static","MaxAudioChannels":"2","CopyTimestamps":true},{"Container":"ts","Type":"Video","AudioCodec":"mp3,aac","VideoCodec":"hevc,h264,av1","Context":"Streaming","Protocol":"hls","MaxAudioChannels":"2","MinSegments":"1","BreakOnNonKeyFrames":false,"ManifestSubtitles":"vtt"},{"Container":"webm","Type":"Video","AudioCodec":"vorbis","VideoCodec":"vpx","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mp4","Type":"Video","AudioCodec":"mp3,aac,opus,flac,vorbis","VideoCodec":"h264","Context":"Static","Protocol":"http"}],"ContainerProfiles":[],"CodecProfiles":[{"Type":"VideoAudio","Codec":"aac","Conditions":[{"Condition":"Equals","Property":"IsSecondaryAudio","Value":"false","IsRequired":"false"}]},{"Type":"VideoAudio","Codec":"flac","Conditions":[{"Condition":"Equals","Property":"IsSecondaryAudio","Value":"false","IsRequired":"false"}]},{"Type":"VideoAudio","Codec":"vorbis","Conditions":[{"Condition":"Equals","Property":"IsSecondaryAudio","Value":"false","IsRequired":"false"}]},{"Type":"VideoAudio","Conditions":[{"Condition":"Equals","Property":"IsSecondaryAudio","Value":"false","IsRequired":"false"}]},{"Type":"Video","Codec":"h264","Conditions":[{"Condition":"EqualsAny","Property":"VideoProfile","Value":"high|main|baseline|constrained baseline|high 10","IsRequired":false},{"Condition":"LessThanEqual","Property":"VideoLevel","Value":"62","IsRequired":false}]},{"Type":"Video","Codec":"hevc","Conditions":[{"Condition":"EqualsAny","Property":"VideoCodecTag","Value":"hvc1|hev1|hevc|hdmv","IsRequired":false}]}],"SubtitleProfiles":[{"Format":"vtt","Method":"Hls"},{"Format":"eia_608","Method":"VideoSideData","Protocol":"hls"},{"Format":"eia_708","Method":"VideoSideData","Protocol":"hls"},{"Format":"vtt","Method":"External","AllowChunkedResponse":true},{"Format":"ass","Method":"External"},{"Format":"ssa","Method":"External"}],"ResponseProfiles":[{"Type":"Video","Container":"m4v","MimeType":"video/mp4"}]}}' ;
curl 'https://127.0.0.1:8096/emby/Items/16184/PlaybackInfo?UserId=b4be2e3b7e1b460da351257f18240d41&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=200000000&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Google+Chrome+Windows&X-Emby-Device-Id=cbe83d8b-9ec9-487f-a0b4-6bf5305035f8&X-Emby-Client-Version=4.9.3.0&X-Emby-Token=token&X-Emby-Language=zh-cn&reqformat=json' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: text/plain' \
  -H 'origin: https://127.0.0.1:8096' \
  -H 'priority: u=1, i' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' \
  --data-raw '{"DeviceProfile":{"MaxStaticBitrate":200000000,"MaxStreamingBitrate":200000000,"MusicStreamingTranscodingBitrate":192000,"DirectPlayProfiles":[{"Container":"mp4,m4v","Type":"Video","VideoCodec":"h264,hevc,av1,vp8,vp9","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"mkv","Type":"Video","VideoCodec":"h264,hevc,av1,vp8,vp9","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"flv","Type":"Video","VideoCodec":"h264","AudioCodec":"aac,mp3"},{"Container":"3gp","Type":"Video","VideoCodec":"","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"mov","Type":"Video","VideoCodec":"h264","AudioCodec":"mp3,aac,opus,flac,vorbis"},{"Container":"opus","Type":"Audio"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3"},{"Container":"mp2,mp3","Type":"Audio","AudioCodec":"mp2"},{"Container":"aac","Type":"Audio","AudioCodec":"aac"},{"Container":"m4a","AudioCodec":"aac","Type":"Audio"},{"Container":"mp4","AudioCodec":"aac","Type":"Audio"},{"Container":"flac","Type":"Audio"},{"Container":"webma,webm","Type":"Audio"},{"Container":"wav","Type":"Audio","AudioCodec":"PCM_S16LE,PCM_S24LE"},{"Container":"ogg","Type":"Audio"},{"Container":"webm","Type":"Video","AudioCodec":"vorbis,opus","VideoCodec":"av1,VP8,VP9"}],"TranscodingProfiles":[{"Container":"aac","Type":"Audio","AudioCodec":"aac","Context":"Streaming","Protocol":"hls","MaxAudioChannels":"2","MinSegments":"1","BreakOnNonKeyFrames":false},{"Container":"aac","Type":"Audio","AudioCodec":"aac","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"opus","Type":"Audio","AudioCodec":"opus","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"wav","Type":"Audio","AudioCodec":"wav","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"opus","Type":"Audio","AudioCodec":"opus","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mp3","Type":"Audio","AudioCodec":"mp3","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"aac","Type":"Audio","AudioCodec":"aac","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"wav","Type":"Audio","AudioCodec":"wav","Context":"Static","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mkv","Type":"Video","AudioCodec":"mp3,aac,opus,flac,vorbis","VideoCodec":"h264,hevc,av1,vp8,vp9","Context":"Static","MaxAudioChannels":"2","CopyTimestamps":true},{"Container":"ts","Type":"Video","AudioCodec":"mp3,aac","VideoCodec":"hevc,h264,av1","Context":"Streaming","Protocol":"hls","MaxAudioChannels":"2","MinSegments":"1","BreakOnNonKeyFrames":false,"ManifestSubtitles":"vtt"},{"Container":"webm","Type":"Video","AudioCodec":"vorbis","VideoCodec":"vpx","Context":"Streaming","Protocol":"http","MaxAudioChannels":"2"},{"Container":"mp4","Type":"Video","AudioCodec":"mp3,aac,opus,flac,vorbis","VideoCodec":"h264","Context":"Static","Protocol":"http"}],"ContainerProfiles":[],"CodecProfiles":[{"Type":"VideoAudio","Codec":"aac","Conditions":[{"Condition":"Equals","Property":"IsSecondaryAudio","Value":"false","IsRequired":"false"}]},{"Type":"VideoAudio","Codec":"flac","Conditions":[{"Condition":"Equals","Property":"IsSecondaryAudio","Value":"false","IsRequired":"false"}]},{"Type":"VideoAudio","Codec":"vorbis","Conditions":[{"Condition":"Equals","Property":"IsSecondaryAudio","Value":"false","IsRequired":"false"}]},{"Type":"VideoAudio","Conditions":[{"Condition":"Equals","Property":"IsSecondaryAudio","Value":"false","IsRequired":"false"}]},{"Type":"Video","Codec":"h264","Conditions":[{"Condition":"EqualsAny","Property":"VideoProfile","Value":"high|main|baseline|constrained baseline|high 10","IsRequired":false},{"Condition":"LessThanEqual","Property":"VideoLevel","Value":"62","IsRequired":false}]},{"Type":"Video","Codec":"hevc","Conditions":[{"Condition":"EqualsAny","Property":"VideoCodecTag","Value":"hvc1|hev1|hevc|hdmv","IsRequired":false}]}],"SubtitleProfiles":[{"Format":"vtt","Method":"Hls"},{"Format":"eia_608","Method":"VideoSideData","Protocol":"hls"},{"Format":"eia_708","Method":"VideoSideData","Protocol":"hls"},{"Format":"vtt","Method":"External","AllowChunkedResponse":true},{"Format":"ass","Method":"External"},{"Format":"ssa","Method":"External"}],"ResponseProfiles":[{"Type":"Video","Container":"m4v","MimeType":"video/mp4"}]}}' ;
curl 'https://127.0.0.1:8096/emby/Users/b4be2e3b7e1b460da351257f18240d41/Items/16184?ExcludeFields=VideoChapters%2CVideoMediaSources%2CMediaStreams&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Google+Chrome+Windows&X-Emby-Device-Id=cbe83d8b-9ec9-487f-a0b4-6bf5305035f8&X-Emby-Client-Version=4.9.3.0&X-Emby-Token=token&X-Emby-Language=zh-cn' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'priority: u=1, i' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' ;
curl 'https://127.0.0.1:8096/web/modules/input/mouse.css?v=4.9.3.0' \
  -H 'accept: text/css,*/*;q=0.1' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'if-modified-since: Wed, 09 Apr 2025 18:39:47 GMT' \
  -H 'if-none-match: "63cf52ec452b0cc1951642f1d108a2a2"' \
  -H 'priority: u=0' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: style' \
  -H 'sec-fetch-mode: no-cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' ;
curl 'https://127.0.0.1:8096/emby/videos/16184/original.mp4?DeviceId=cbe83d8b-9ec9-487f-a0b4-6bf5305035f8&MediaSourceId=mediasource_16184&PlaySessionId=82c1ab208d754b8fa7dbedd9aa05b482&api_key=token' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'priority: i' \
  -H 'range: bytes=0-' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: video' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' ;
curl 'https://127.0.0.1:8096/emby/videos/16184/original.mp4?DeviceId=cbe83d8b-9ec9-487f-a0b4-6bf5305035f8&MediaSourceId=mediasource_16184&PlaySessionId=82c1ab208d754b8fa7dbedd9aa05b482&api_key=token' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'priority: i' \
  -H 'range: bytes=3151101952-' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: video' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' ;
curl 'https://127.0.0.1:8096/emby/videos/16184/original.mp4?DeviceId=cbe83d8b-9ec9-487f-a0b4-6bf5305035f8&MediaSourceId=mediasource_16184&PlaySessionId=82c1ab208d754b8fa7dbedd9aa05b482&api_key=token' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'priority: i' \
  -H 'range: bytes=32768-' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: video' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' ;
curl 'https://127.0.0.1:8096/emby/videos/16184/original.mp4?DeviceId=cbe83d8b-9ec9-487f-a0b4-6bf5305035f8&MediaSourceId=mediasource_16184&PlaySessionId=82c1ab208d754b8fa7dbedd9aa05b482&api_key=token' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'priority: i' \
  -H 'range: bytes=2041446400-' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: video' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' ;
curl 'https://127.0.0.1:8096/emby/Sessions/Playing?X-Emby-Client=Emby+Web&X-Emby-Device-Name=Google+Chrome+Windows&X-Emby-Device-Id=cbe83d8b-9ec9-487f-a0b4-6bf5305035f8&X-Emby-Client-Version=4.9.3.0&X-Emby-Token=token&X-Emby-Language=zh-cn&reqformat=json' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: text/plain' \
  -H 'origin: https://127.0.0.1:8096' \
  -H 'priority: u=1, i' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' \
  --data-raw '{"VolumeLevel":100,"IsMuted":false,"IsBackgroundPlayback":false,"IsPaused":false,"RepeatMode":"RepeatNone","SleepTimerMode":"None","Shuffle":false,"SubtitleOffset":0,"PlaybackRate":1,"MaxStreamingBitrate":200000000,"PositionTicks":18887893570,"PlaybackStartTimeTicks":17778045758080000,"SubtitleStreamIndex":-1,"AudioStreamIndex":1,"BufferedRanges":[{"start":18868800000,"end":18891200000},{"start":19081780000,"end":19095860000}],"SeekableRanges":[{"start":0,"end":29473600000}],"PlayMethod":"DirectStream","PlaySessionId":"82c1ab208d754b8fa7dbedd9aa05b482","MediaSourceId":"mediasource_16184","CanSeek":true,"ItemId":"16184","PlaylistIndex":0,"PlaylistLength":38,"NowPlayingQueue":[{"Id":"16184","PlaylistItemId":"playlistItem38"},{"Id":"16185","PlaylistItemId":"playlistItem39"},{"Id":"16186","PlaylistItemId":"playlistItem40"},{"Id":"16187","PlaylistItemId":"playlistItem41"},{"Id":"16188","PlaylistItemId":"playlistItem42"},{"Id":"16189","PlaylistItemId":"playlistItem43"},{"Id":"16190","PlaylistItemId":"playlistItem44"},{"Id":"16191","PlaylistItemId":"playlistItem45"},{"Id":"16192","PlaylistItemId":"playlistItem46"},{"Id":"16193","PlaylistItemId":"playlistItem47"},{"Id":"16194","PlaylistItemId":"playlistItem48"},{"Id":"16195","PlaylistItemId":"playlistItem49"},{"Id":"16196","PlaylistItemId":"playlistItem50"},{"Id":"16197","PlaylistItemId":"playlistItem51"},{"Id":"16198","PlaylistItemId":"playlistItem52"},{"Id":"16199","PlaylistItemId":"playlistItem53"},{"Id":"16200","PlaylistItemId":"playlistItem54"},{"Id":"16201","PlaylistItemId":"playlistItem55"},{"Id":"16202","PlaylistItemId":"playlistItem56"},{"Id":"16203","PlaylistItemId":"playlistItem57"},{"Id":"16204","PlaylistItemId":"playlistItem58"},{"Id":"16205","PlaylistItemId":"playlistItem59"},{"Id":"16206","PlaylistItemId":"playlistItem60"},{"Id":"16207","PlaylistItemId":"playlistItem61"},{"Id":"16208","PlaylistItemId":"playlistItem62"},{"Id":"16209","PlaylistItemId":"playlistItem63"},{"Id":"16210","PlaylistItemId":"playlistItem64"},{"Id":"16211","PlaylistItemId":"playlistItem65"},{"Id":"16212","PlaylistItemId":"playlistItem66"},{"Id":"16213","PlaylistItemId":"playlistItem67"},{"Id":"16214","PlaylistItemId":"playlistItem68"},{"Id":"16215","PlaylistItemId":"playlistItem69"},{"Id":"16216","PlaylistItemId":"playlistItem70"},{"Id":"16217","PlaylistItemId":"playlistItem71"},{"Id":"16218","PlaylistItemId":"playlistItem72"},{"Id":"16219","PlaylistItemId":"playlistItem73"},{"Id":"16220","PlaylistItemId":"playlistItem74"},{"Id":"16221","PlaylistItemId":"playlistItem75"}]}' ;
curl 'https://127.0.0.1:8096/emby/Sessions/Playing/Progress?X-Emby-Client=Emby+Web&X-Emby-Device-Name=Google+Chrome+Windows&X-Emby-Device-Id=cbe83d8b-9ec9-487f-a0b4-6bf5305035f8&X-Emby-Client-Version=4.9.3.0&X-Emby-Token=token&X-Emby-Language=zh-cn&reqformat=json' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: text/plain' \
  -H 'origin: https://127.0.0.1:8096' \
  -H 'priority: u=1, i' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' \
  --data-raw '{"VolumeLevel":100,"IsMuted":false,"IsBackgroundPlayback":false,"IsPaused":false,"RepeatMode":"RepeatNone","SleepTimerMode":"None","Shuffle":false,"SubtitleOffset":0,"PlaybackRate":1,"MaxStreamingBitrate":200000000,"PositionTicks":18890414100,"PlaybackStartTimeTicks":17778045758080000,"SubtitleStreamIndex":-1,"AudioStreamIndex":1,"BufferedRanges":[{"start":18868800000,"end":18923200000},{"start":19081780000,"end":19221740000}],"SeekableRanges":[{"start":0,"end":29473600000}],"PlayMethod":"DirectStream","PlaySessionId":"82c1ab208d754b8fa7dbedd9aa05b482","MediaSourceId":"mediasource_16184","CanSeek":true,"ItemId":"16184","EventName":"timeupdate","PlaylistIndex":0,"PlaylistLength":38}' ;
curl 'https://127.0.0.1:8096/emby/Items/16184/ThumbnailSet?MediaSourceId=mediasource_16184&Width=400&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Google+Chrome+Windows&X-Emby-Device-Id=cbe83d8b-9ec9-487f-a0b4-6bf5305035f8&X-Emby-Client-Version=4.9.3.0&X-Emby-Token=token&X-Emby-Language=zh-cn' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'priority: u=1, i' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' ;
curl 'https://127.0.0.1:8096/emby/Sessions/Playing/Progress?X-Emby-Client=Emby+Web&X-Emby-Device-Name=Google+Chrome+Windows&X-Emby-Device-Id=cbe83d8b-9ec9-487f-a0b4-6bf5305035f8&X-Emby-Client-Version=4.9.3.0&X-Emby-Token=token&X-Emby-Language=zh-cn&reqformat=json' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'content-type: text/plain' \
  -H 'origin: https://127.0.0.1:8096' \
  -H 'priority: u=1, i' \
  -H 'referer: https://127.0.0.1:8096/web/index.html' \
  -H 'sec-ch-ua: "Google Chrome";v="147", "Not.A/Brand";v="8", "Chromium";v="147"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-origin' \
  -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0.0.0 Safari/537.36' \
  --data-raw '{"VolumeLevel":100,"IsMuted":false,"IsBackgroundPlayback":false,"IsPaused":true,"RepeatMode":"RepeatNone","SleepTimerMode":"None","Shuffle":false,"SubtitleOffset":0,"PlaybackRate":1,"MaxStreamingBitrate":200000000,"PositionTicks":18899587180,"PlaybackStartTimeTicks":17778045758080000,"SubtitleStreamIndex":-1,"AudioStreamIndex":1,"BufferedRanges":[{"start":18868800000,"end":18929600000},{"start":19081780000,"end":19230320000}],"SeekableRanges":[{"start":0,"end":29473600000}],"PlayMethod":"DirectStream","PlaySessionId":"82c1ab208d754b8fa7dbedd9aa05b482","MediaSourceId":"mediasource_16184","CanSeek":true,"ItemId":"16184","EventName":"pause","PlaylistIndex":0,"PlaylistLength":38}'
